### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by jlnhnng** [linode/apl-core#1217]
**Is your feature request related to a problem? Please describe.** 
Container Image for ARM missing, thus, problem with installing on ARM-based infrastructure and issues with helm uninstall because 'delete-pods' are not available as ARM images either. 

**Describe the solution you'd like**
Please build container Images in ARM too. 

**Describe alternatives you've considered**
Build ARM images by myself or not use Otomi. 

**Additional context**

**Comment by j-zimnowoda** [comment]
Hi @jlnhnng thanks for letting us know.
Do you have any recommendations for us for building the ARM images ?

**Comment by jlnhnng** [comment]
Hi @j-zimnowoda, you can build Multi-platform images with your **Build and publish Docker** GitHub Action. Here is a good explanation on how to do that from Docker https://docs.docker.com/build/ci/github-actions/multi-platform/ 
Cheers

**Comment by j-zimnowoda** [comment]
Cool, thanks for hint. We will try it out.
