### ISSUE TITLE
Keycloak error on installation on Kind

### ISSUE THREAD

**Issue by ams0** [linode/apl-core#1248]
**Describe the bug:** (a clear and concise description of what the bug is)

Otomi fails to install because Keycloak chart fails

**To Reproduce**

1. Install a Kind cluster with 1 master and 3 workers, with Cilium CNI and MetalLB
2. Install Otomi with the following values.yaml

```
cluster:
  k8sVersion: "1.25"
  name: "kind-kind"
  provider: "custom"
otomi:
  hasExternalDNS: true
  adminPassword: <redacted>
apps:
  metrics-server:
    enabled: true
    _rawValues:
      extraArgs:
        kubelet-preferred-address-types: InternalIP
        kubelet-insecure-tls: true
```
3. Otomi fails at bringing up `keycloack-0` pod (database pod comes us fine).

**Expected behavior:** (a clear and concise description of what you expected to happen)

**Screenshots:** (if applicable, add screenshots to help explain your problem)

```
keycloak-0 keycloak # A fatal error has been detected by the Java Runtime Environment:
keycloak-0 keycloak #
keycloak-0 keycloak #  SIGSEGV (0xb) at pc=0x00007ffffe497026, pid=89, tid=143
keycloak-0 keycloak #
keycloak-0 keycloak # JRE version: OpenJDK Runtime Environment 18.9 (11.0.13+8) (build 11.0.13+8-LTS)
keycloak-0 keycloak # Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.13+8-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
keycloak-0 keycloak # Problematic frame:
keycloak-0 keycloak # V  [libjvm.so+0x7d0026]  G1ParScanThreadState::copy_to_survivor_space(InCSetState, oopDesc*, markOopDesc*)+0x56
keycloak-0 keycloak #
keycloak-0 keycloak # Core dump will be written. Default location: /opt/jboss/keycloak/core
keycloak-0 keycloak #
keycloak-0 keycloak # An error report file with more information is saved as:
keycloak-0 keycloak # /opt/jboss/keycloak/hs_err_pid89.log
keycloak-0 keycloak #
keycloak-0 keycloak # If you would like to submit a bug report, please visit:
keycloak-0 keycloak #   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-11-openjdk
keycloak-0 keycloak #
keycloak-0 keycloak /opt/jboss/tools/databases/change-database.sh: line 7:    89 Aborted                 (core dumped) bin/jboss-cli.sh --file=/opt/jboss/tools/cli/databases/$DB_VENDOR/standalone-configuration.cli
```

**Cluster(s):**

kind on Mac M1max (64gb RAM) Docker Desktop with 10 vCPU, 32gb ram and 100GB of disk space

**Versions:** (seen in console's `/settings`)

- Core Version 0.55.1

**Desktop:** (if relevant)

- OS:  macOS 14.0

**Additional context:** (add any other context about the problem here)

Full keycloak error log is here: https://pastebin.com/ACByrkjL

**Comment by j-zimnowoda** [comment]
Hi @ams0 

It appears that you are utilizing a machine equipped with an ARM CPU. Keycloak has introduced ARM support starting from [version 18](https://github.com/keycloak/keycloak/discussions/8846). Currently, Otomi is running on version 15.

We are actively engaged in the process of upgrading Keycloak and anticipate completing it in the near future. I will leave this ticket open until the upgrade is successfully completed.

Best regards,

**Comment by ams0** [comment]
Can I submit a PR? This being an open source project :) can you point me in the right direction?

**Comment by j-zimnowoda** [comment]
Yes, of course you help will be very much appreciated :) 

In order to submit PR you need to fork this repo and submit PR from the fork.
There is also documentation for developers: https://github.com/redkubes/otomi-core/blob/main/docs/README.md

By the way, the support of the new keycloak version is almost there. 
You could actually try to deploy Otomi by using the `kc_upgrade` image tag and the following values from otomi helm chart.
```
cluster:
  name: 'dev'
  k8sContext: notUsed
otomi:
  version: 'kc_upgrade'
```

**Comment by j-zimnowoda** [comment]
The ARM compatibility issue is also here #1217.
