### ISSUE TITLE
Error creating workload with top level "labels" in helm values

### ISSUE THREAD

**Issue by mcalr3** [linode/apl-core#1369]
**Describe the bug:** (a clear and concise description of what the bug is)

When creating a workload in Otomi, where the BYOC chart has a top level "labels" value in the chart, Otomi produces an error message. It looks like Otomi is not expecting any helm chart to have a top level "labels" key in the yaml.

**Screenshots:** (if applicable, add screenshots to help explain your problem)
<img width="1222" alt="image" src="https://github.com/redkubes/otomi-core/assets/19345458/dbfa8b39-7d91-4b8e-91d8-65324745bb17">

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [1.1.4]
- Console Version: [1.4.0]
- API version: [1.2.0]

**Desktop:** (if relevant)

- OS: [macOS]
- Browser [chrome]
- Version [sonoma]

**Comment by CasLubbers** [comment]
Hi,

Thank you for your contribution, and apologies for the delayed response. We no longer support version 1.1.x. This issue has been fully resolved in version 2.11.x and will also be included in the upcoming 3.x.x release.

Please consider upgrading to one of these versions.

Best regards,
Cas
